### ISSUE TITLE
Protocol Derive missing Cargo.toml

### ISSUE THREAD

**Issue by Zanctarian** [netherite-rs/netherite#1]
I was attempting to build this repo to check it out but it seems you forgot to upload the cargo file for protocol_derive, figured I'd let you know

**Comment by Revxrsal** [comment]
The Cargo.toml seems to be present. Can you explain more? 

Also, the project is by no means in any stable state, changes are made mostly locally and nothing is guaranteed to remain working until it's finalized. Considering that the project also contains many design mistakes, changes could be breaking (although I try to make sure they're not much)

**Comment by Zanctarian** [comment]
It's present because it was added 5 minutes ago.

![image](https://github.com/netherite-rs/netherite/assets/44514121/1fc5ca7f-8553-4865-8641-cb3ef6b40dde)
![image](https://github.com/netherite-rs/netherite/assets/44514121/8245ca14-a776-4914-ba27-205c49a2dceb)

**Comment by Revxrsal** [comment]
Oh, woops. My bad.
